services:
  app:
    image: node:lts
    command: sh -c "npm install && npm run build && npm run start:prod"
    container_name: pomodoro-api
    ports:
      - 3002
    working_dir: /app
    build: .
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: scoobydoo